approvedGitRepositories:
  - "**"

defaultSemverRangePrefix: ""

enableGlobalCache: false

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: "2w"

yarnPath: .yarn/releases/yarn-4.17.1.cjs
