function t(t,r){if(1==t.length)return t[0];const i=new Uint8Array(r);for(let r=0,n=0;t.length>r;++r){const s=t[r];i.set(s,n),n+=s.length}return i}function r(t){
/*! @__PURE__ */
const r=t instanceof Uint8Array?t:t instanceof ArrayBuffer?new Uint8Array(t):void 0,i=new w({...u.buffer,dictionary:r});return i.init(l),i}async function i(t=0,i){if(!l){const t=u.t();l=t instanceof Promise?await t:t}y.has(t)||(y.set(t,new Map),d.set(t,[]));const n=y.get(t),s=d.get(t);for(let r=0;s.length>r;++r)if(!s[r])return s[r]=!0,[n.get(r),r,t];const e=r(t>0?i?.dictionary||A.get(t):void 0);if(s.length>2)return[e,-1,t];const o=s.length;return n.set(o,e),s.push(!0),[e,o,t]}function n(t,r){const i=d.get(r);i&&(i[t]=!1)}var s,e,o,c,a,h,f,w,u,y,d,m,l,A,_,S,p,U,b,z,x,M;import{readFileSync as P}from"node:fs";s=Error,e=(t,r,i)=>{
/*! @__PURE__ */
let n=0,s=0;for(;i>n;++n)s|=t[r++]<<(n<<3);return s},o=t=>{const r=t[4],i=r>>5&1,n=3&r,s=r>>6;return e(t,6-i+n==3?4:n,s?1<<s:i)+(1==s&&256)},c=t=>{
/*! @__PURE__ */
if(3126568==(t[0]|t[1]<<8|t[2]<<16)&&253==t[3]){const r=t[4],i=r>>5&1,n=3&r,o=r>>6,c=6-i,a=3==n?4:n,h=e(t,c,a),f=e(t,c+a,o?1<<o:i)+(1==o&&256);let w=f;if(!i){const r=1<<10+(t[5]>>3);w=r+(r>>3)*(7&t[5])}if(f>1e7)throw new s("win 2 large");return{d:h,u:w,e:f}}throw new s("bad zstd dat")},a=2097152,h=9830464,f={buf:new Uint8Array(0),in_offset:0},w=class{i;o;h;m=8192;l=8208;A;_=0;S=0;p=0;U=0;constructor(t={}){this.A=t.dictionary,this._=Math.max(t.maxSrcSize,629149696),this.S=Math.max(t.maxDstSize,629149696)}init(t){return this.M(new WebAssembly.Instance(t,{env:{}}))}P(t,r){return this.M(t)}M(t){this.i=t.exports;const r=this.i.memory;this.o=new Uint8Array(r.buffer),this.h=new Uint32Array(r.buffer);const i=this.i.getInBufferPtr;if("function"==typeof i&&(this.m=i(),this.l=this.m+16),this.i._initialize(),this.A){const t=this.A.length;if(t>a)throw new s("dict>2mb");const r=this.i.malloc(t);this.o.set(this.A,r),this.i.cd(r,t)}return this.p=this.i.malloc(a),this.U=this.p+a,this}decompressSync(t,r){if(!this.i)throw new s("not init");const i=t.length;if(i>this._)throw new s("comp dat>maxSrcSize lim");if(r||(r=o(t)),r>h||i>a)return this.decompressStream(t,!0).buf;const n=this.U;this.i.pb(n),this.o.set(t,this.p);const e=this.i.dS(n,h,this.p,i);if(0>e)throw new s("dec err "+e);return this.o.slice(n,n+e)}v(t,r,i){const n=t>>>2;this.h[n]=r,this.h[n+1]=i,this.h[n+2]=0}D(t){return this.h[t+8>>>2]}decompressStream(r,i=!1){if(!this.i)throw new s("not init");i&&(this.i.re(),this.i.pb(this.U));const n=r.length||0;if(0==n)return f;const e=[];let o=0,c=0;const a=this.p+262150;let h=a;const w=a+655360;let u=0;for(;n>c;){const t=Math.min(n-c,262150);for(this.o.set(r.subarray(c,c+t),this.p),this.v(this.m,this.p,t),h==a&&this.v(this.l,h,917501);this.D(this.m)<t;){const t=this.i.ds();if(0>t)throw new s("dec err "+t);const r=this.D(this.l);if(o+=h==a?r:r-u,u=r,r>0&&(h=a+r,w>h||(e.push(this.o.slice(a,h)),h=a,this.v(this.l,h,917501)),o>this.S))throw new s("dec size>maxDstSize lim")}c+=t}return h!=a&&e.push(this.o.slice(a,h)),{buf:t(e,o),in_offset:n}}B(){this.i=this.o=this.h=null}},u={t:null,buffer:{maxSrcSize:0,maxDstSize:0},dictionaries:[]},y=new Map,d=new Map,m=!1,A=new Map,_=async t=>{if(
/*! @__PURE__ */
t.maxSrcSize&&(u.buffer.maxSrcSize=t.maxSrcSize),t.maxDstSize&&(u.buffer.maxDstSize=t.maxDstSize),t.dictionaries)for(const r of t.dictionaries){const t=await S(r),i=p(t);i>0&&A.set(i,t)}},S=async t=>{
/*! @__PURE__ */
if(t instanceof Uint8Array)return t;if(t instanceof ArrayBuffer)return new Uint8Array(t);const r=await fetch(t);return new Uint8Array(await r.arrayBuffer())},p=t=>{
/*! @__PURE__ */
if(6>t.length)return 0;try{const r=c(t),i="object"==typeof r?r.d:0;return i>0&&A.set(i,t),i}catch{return 0}},U=async(t={})=>(
/*! @__PURE__ */
m||(l=await u.t(t.wasmPath),m=!0),r(t.dictionary)),b=t=>t instanceof Uint8Array?t:ArrayBuffer.isView(t)?new Uint8Array(t.buffer,t.byteOffset,t.byteLength):new Uint8Array(t);class v{readable;writable;constructor(r){let e,o=-1,a=0,h=!0;const f=[];let w={d:0,u:0,e:-1},u=0,y=0,d=0,m=262144;const{readable:l,writable:A}=new TransformStream({async transform(t,n){const l=b(t);if(u+=l.length,f.push(l),++d,u>=12){if(-1==w.e){const t=new Uint8Array(u);let r=0;for(let i=0;d>i;++i)t.set(f[i],r),r+=f[i].length;w=c(t),m=Math.max(m,w.e,w.u>>4,1<<17)}if(u>=m&&-1!=w.e){if(e){const t=e.decompressStream(l,!1).buf;return void(t.length>0&&n.enqueue(t))}try{h&&(a=p(l),[e,o,a]=await i(a,r));const t=e.decompressStream(l,h).buf;y+=t.length,n.enqueue(t),h=!1}catch(t){n.error(new s("dec err "+t))}}}},async flush(i){if(0==y&&u>6)try{const n=await x(t(f,u),!0,r);i.enqueue(n.buf)}catch(t){i.error(new s("dec err "+t))}else-1==o?e?.B():n(o,a);i.terminate()}});this.readable=l,this.writable=A}}z=async(t,r)=>(await x(t,!0,r)).buf,x=async(t,r=!1,s)=>{
/*! @__PURE__ */
const e=p(t),[o,c]=await i(e,s),a=o.decompressStream(t,r);return-1==c?o.B():n(c,e),a},M=(t,i,n)=>{
/*! @__PURE__ */
const s=p(t);return(y.get(s)?.get(0)||r(s>0?n?.dictionary||A.get(s):void 0)).decompressSync(t,i)},u.t=()=>{const t=new URL("./zstd-decoder-perf.wasm",import.meta.url);return new WebAssembly.Module(P(t))};export{_ as setupZstdDecoder,M as decompressSync,x as decompressStream,z as decompress,U as createDecoder,v as ZstdDecompressionStream,w as ZstdDecoder};