function t(t,i){if(1==t.length)return t[0];const r=new Uint8Array(i);for(let i=0,n=0;t.length>i;++i){const s=t[i];r.set(s,n),n+=s.length}return r}function i(t){
/*! @__PURE__ */
const i=t instanceof Uint8Array?t:t instanceof ArrayBuffer?new Uint8Array(t):void 0,r=new s({...e.buffer,dictionary:i});return r.init(h),r}async function r(t=0,r){if(!h){const t=e.t();h=t instanceof Promise?await t:t}o.has(t)||(o.set(t,new Map),a.set(t,[]));const n=o.get(t),s=a.get(t);for(let i=0;s.length>i;++i)if(!s[i])return s[i]=!0,[n.get(i),i,t];const c=i(t>0?r?.dictionary||f.get(t):void 0);if(s.length>2)return[c,-1,t];const w=s.length;return n.set(w,c),s.push(!0),[c,w,t]}function n(t,i){const r=a.get(i);r&&(r[t]=!1)}var s,e,o,a,c,h,f,w,u,y,d,l,m,A,_,S=Error,U=(t,i,r)=>{
/*! @__PURE__ */
let n=0,s=0;for(;r>n;++n)s|=t[i++]<<(n<<3);return s},b=t=>{
/*! @__PURE__ */
if(3126568==(t[0]|t[1]<<8|t[2]<<16)&&253==t[3]){const i=t[4],r=i>>5&1,n=3&i,s=i>>6,e=6-r,o=3==n?4:n,a=U(t,e,o),c=U(t,e+o,s?1<<s:r)+(1==s&&256);let h=c;if(!r){const i=1<<10+(t[5]>>3);h=i+(i>>3)*(7&t[5])}if(c>1e7)throw new S("win 2 large");return{d:a,u:h,e:c}}throw new S("bad zstd dat")},p=2097152,z=9830464,x={buf:new Uint8Array(0),in_offset:0};s=class{i;o;h;l=8192;m=8208;A;_=0;S=0;U=0;p=0;constructor(t={}){this.A=t.dictionary,this._=Math.max(t.maxSrcSize,629149696),this.S=Math.max(t.maxDstSize,629149696)}init(t){return this.M(new WebAssembly.Instance(t,{env:{}}))}P(t,i){return this.M(t)}M(t){this.i=t.exports;const i=this.i.memory;this.o=new Uint8Array(i.buffer),this.h=new Uint32Array(i.buffer);const r=this.i.getInBufferPtr;if("function"==typeof r&&(this.l=r(),this.m=this.l+16),this.i._initialize(),this.A){const t=this.A.length;if(t>p)throw new S("dict>2mb");const i=this.i.malloc(t);this.o.set(this.A,i),this.i.cd(i,t)}return this.U=this.i.malloc(p),this.p=this.U+p,this}decompressSync(t,i){if(!this.i)throw new S("not init");const r=t.length;if(r>this._)throw new S("comp dat>maxSrcSize lim");if(i||(i=(t=>{const i=t[4],r=i>>5&1,n=3&i,s=i>>6;return U(t,6-r+n==3?4:n,s?1<<s:r)+(1==s&&256)})(t)),i>z||r>p)return this.decompressStream(t,!0).buf;const n=this.p;this.i.pb(n),this.o.set(t,this.U);const s=this.i.dS(n,z,this.U,r);if(0>s)throw new S("dec err "+s);return this.o.slice(n,n+s)}v(t,i,r){const n=t>>>2;this.h[n]=i,this.h[n+1]=r,this.h[n+2]=0}D(t){return this.h[t+8>>>2]}decompressStream(i,r=!1){if(!this.i)throw new S("not init");r&&(this.i.re(),this.i.pb(this.p));const n=i.length||0;if(0==n)return x;const s=[];let e=0,o=0;const a=this.U+262150;let c=a;const h=a+655360;let f=0;for(;n>o;){const t=Math.min(n-o,262150);for(this.o.set(i.subarray(o,o+t),this.U),this.v(this.l,this.U,t),c==a&&this.v(this.m,c,917501);this.D(this.l)<t;){const t=this.i.ds();if(0>t)throw new S("dec err "+t);const i=this.D(this.m);if(e+=c==a?i:i-f,f=i,i>0&&(c=a+i,h>c||(s.push(this.o.slice(a,c)),c=a,this.v(this.m,c,917501)),e>this.S))throw new S("dec size>maxDstSize lim")}o+=t}return c!=a&&s.push(this.o.slice(a,c)),{buf:t(s,e),in_offset:n}}B(){this.i=this.o=this.h=null}},e={t:null,buffer:{maxSrcSize:0,maxDstSize:0},dictionaries:[]},o=new Map,a=new Map,c=!1,f=new Map,w=async t=>{if(
/*! @__PURE__ */
t.maxSrcSize&&(e.buffer.maxSrcSize=t.maxSrcSize),t.maxDstSize&&(e.buffer.maxDstSize=t.maxDstSize),t.dictionaries)for(const i of t.dictionaries){const t=await u(i),r=y(t);r>0&&f.set(r,t)}},u=async t=>{
/*! @__PURE__ */
if(t instanceof Uint8Array)return t;if(t instanceof ArrayBuffer)return new Uint8Array(t);const i=await fetch(t);return new Uint8Array(await i.arrayBuffer())},y=t=>{
/*! @__PURE__ */
if(6>t.length)return 0;try{const i=b(t),r="object"==typeof i?i.d:0;return r>0&&f.set(r,t),r}catch{return 0}},d=async(t={})=>(
/*! @__PURE__ */
c||(h=await e.t(t.wasmPath),c=!0),i(t.dictionary)),l=t=>t instanceof Uint8Array?t:ArrayBuffer.isView(t)?new Uint8Array(t.buffer,t.byteOffset,t.byteLength):new Uint8Array(t);class M{readable;writable;constructor(i){let s,e=-1,o=0,a=!0;const c=[];let h={d:0,u:0,e:-1},f=0,w=0,u=0,d=262144;const{readable:m,writable:_}=new TransformStream({async transform(t,n){const m=l(t);if(f+=m.length,c.push(m),++u,f>=12){if(-1==h.e){const t=new Uint8Array(f);let i=0;for(let r=0;u>r;++r)t.set(c[r],i),i+=c[r].length;h=b(t),d=Math.max(d,h.e,h.u>>4,1<<17)}if(f>=d&&-1!=h.e){if(s){const t=s.decompressStream(m,!1).buf;return void(t.length>0&&n.enqueue(t))}try{a&&(o=y(m),[s,e,o]=await r(o,i));const t=s.decompressStream(m,a).buf;w+=t.length,n.enqueue(t),a=!1}catch(t){n.error(new S("dec err "+t))}}}},async flush(r){if(0==w&&f>6)try{const n=await A(t(c,f),!0,i);r.enqueue(n.buf)}catch(t){r.error(new S("dec err "+t))}else-1==e?s?.B():n(e,o);r.terminate()}});this.readable=m,this.writable=_}}m=async(t,i)=>(await A(t,!0,i)).buf,A=async(t,i=!1,s)=>{
/*! @__PURE__ */
const e=y(t),[o,a]=await r(e,s),c=o.decompressStream(t,i);return-1==a?o.B():n(a,e),c},_=(t,r,n)=>{
/*! @__PURE__ */
const s=y(t);return(o.get(s)?.get(0)||i(s>0?n?.dictionary||f.get(s):void 0)).decompressSync(t,r)},e.t=async t=>{const i=t||new URL("./zstd-decoder-perf.wasm",import.meta.url).href,r=await fetch(i);return await WebAssembly.compileStreaming(r)};export{w as setupZstdDecoder,_ as decompressSync,A as decompressStream,m as decompress,d as createDecoder,M as ZstdDecompressionStream,s as ZstdDecoder};